#!/bin/bash

REMOTE=origin
BASE=master
TARGET=testing-0.5

echo $REMOTE/$BASE to $TARGET
echo "check settings and PACKAGES"
exit

PACKAGES="yavdr-addon-asunder \
yavdr-addon-chromium \
yavdr-addon-claws-mail \
yavdr-addon-dvdrip \
yavdr-addon-helix \
yavdr-addon-mame \
yavdr-addon-mediathek \
yavdr-addon-performous \
yavdr-addon-pidgin \
yavdr-addon-pip \
yavdr-addon-semsix \
yavdr-addon-simfy \
yavdr-addon-skype \
yavdr-addon-supertuxkart \
yavdr-addon-thunderbird \
yavdr-addon-tuxracer \
yavdr-addon-vlc \
yavdr-addon-wormux \
yavdr-addon-youtube \
yavdr-backup \
yavdr-base \
yavdr-desktop \
yavdr-dev \
yavdr-dvb \
yavdr-essential \
yavdr-hardware-displaylink \
yavdr-hardware-mdm166a \
yavdr-hardware-sundtek \
yavdr-i18n \
yavdr-plymouth-theme \
yavdr-remote \
yavdr-utils \
yavdr-webfrontend \
vdr-plugin-dbus \
vdr-plugin-dbus2vdr \
vdr-plugin-ddci \
vdr-plugin-dynamite \
vdr-plugin-noepg \
vdr-plugin-pvrinput \
vdr-plugin-restfulapi \
vdr-plugin-shutdown \
vdr-plugin-sundtek"

for PACKAGE in $PACKAGES
do
  if [ -d $PACKAGE ]; then
    echo processing $PACKAGE
    cd $PACKAGE
    git fetch --all
    git checkout $BASE
    git pull
    git checkout -b $TARGET $REMOTE/$BASE
    git push -u $REMOTE $TARGET
    cd ..
  else
    echo skipping $PACKAGE
  fi
done

